import sys
import os

albums = ["2 days in Jalna", "3 days in Mumbai and Palghar", "7 days in Jalna", "A complete night at marine drive + AndhaDhun movie", "a misc json", "a misc photos", "AA Felicitation", "All NSS meet 2018", "Archive", "Belgium walles with vinu and dinner at the Finch", "Bhavana Masi marriage", "Bhavana masi photos", "Bhua_s 25th anniversary!!", "Boathouse with Arnav, Shinde and Ankur", "Boathouse with gangu", "Chambal garden, Kota", "Congratulations harsh (mentor)", "Diwali week at Jalna 2020 (corona lockdown)", "Donation 1 to front labour union", "Friday in Deomurti", "Friday in Mumbai", "Friday night in Mumbai", "Friendship day 2017", "Fun in Jalna", "HA council handing over, 2019", "Handing over treat 1", "Hanging gardens and the temple", "Hoorda party in Sugras", "Imagica theme park", "Jee class 11", "Juhu beach with Mahavir and Vinisha", "Kota days", "Kurta Day 2019", "Lohagarh", "Mahavir good pics", "Marine drive trip with floories", "Mining near saraswati mandir", "Monday afternoon in Jalna", "Monday afternoon in Mumbai", "Motibagh", "Mount Abu", "Nishtha photos", "NSS heads handing over", "Old memories from VCR", "Ooze ni gaye, trapped", "Organised", "Persian Dhaba", "Photos from 2009", "Photos from 2010", "Photos from 2012", "Photos from 2013", "Photos from 2014", "Photos from 2015", "Photos from 2016", "Photos from 2017", "Photos from 2021", "Photos from 2022", "Pratyush pics", "Prithvi cafe, juhu", "R city with Chirag", "Rakshabandhan in Bengaluru", "Rakshabandhan in Palghar 2019", "Rucha ka budday!", "Saturday afternoon in Mumbai", "Saturday in Jalna", "Saturday in Mumbai", "Siryaari", "Solapur Camp fire", "Solapur get together 2021", "Sunday afternoon in Bengaluru", "Sunday afternoon in Thane", "Sunday in Bengaluru", "Sunday in Igatpuri", "Sunday in Kota", "Sunday in Mumbai", "Sunday in Shegaon", "Sunday morning at Sameer Hills", "Sunday trip in Matheran", "Team Photo session_", "Thursday afternoon in Mumbai", "Thursday in Jalna", "Treat at Absolute Barbeques", "Treat at Utsav", "Trek at Matheran", "Trek to Prabalgad", "Trip at SoU", "Trip to Bandra, Worli", "Trip to Bhivpuri", "Trip to Bhogaon", "Trip to Chennai", "Trip to CST with Jatin and Tanay", "Trip to Indore and Kota", "Trip to Indore Zoo", "Trip to Jaipur and Kota", "Trip to Lavasa", "Trip to Lonavala", "Trip to Mahabaleshwar", "Trip to Mumbai and Anneswara", "Trip to Palghar during intern", "Trip to Sanjay Gandhi National Park", "Trip to Shegaon", "Trip to Solapur", "Trip to Tarkarli", "Tuesday afternoon in Mumbai", "Vihogaon falls with NSS team", "Visit to Sangi Mali in Solapur", "Waterstones waali Mumbai trip", "Weekend in Chitradurga and Davanagere", "Weekend in Jalna", "Weekend in Mumbai", "Weekend in Mumbai and Atvan", "Weekend in Palghar and Satpati"]


for album in albums:
    directory = os.path.join("D:/Takeout/Google Photos", album)
    test = os.listdir(directory)

    for item in test:
        if item.endswith(".json"):
            os.remove(os.path.join(directory, item))
